pipeline{
  agent any
  tools{
    maven 'Maven-Local'
    jdk 'Java-Local'
  }
  stages{
    stage('Checkout'){
      steps{
        echo 'Cloning code from GitHub..'
        git branch: 'main',url:'https://github.com/Rajanik-maker/NewRepo.git'
          }
    }

    stage('Build'){
      steps {
        echo 'Compiling the Project...'
        dir('TestFirstProject'){
        bat 'mvn clean compile'
      }
    }
    }
    
    stage('Test'){
      steps{
        echo 'Running Unit tests..'
        dir('TestFirstProject'){
        bat 'mvn test'
      }
    }
    }
    stage('package'){
      steps {
        echo 'Packaging the Project...'
        dir('TestFirstProject'){
        bat 'mvn package'
      }
      }
      post {
        success {
          echo 'Archiving the JAR files...'
          archiveArtifacts artifacts: 'TestFirstProject/target/*.jar',fingerprint: true
        }
      }
    }
  }
}
