pipeline{
  agent any
  tools{
    maven 'Maven-Local'
    jdk 'Java-Local'
  }
  stages{
    stage('Checkout'){
      steps{
        echo 'Cloning code from GitHub...'
        git branch: 'main',url:'https://github.com/Rajanik-maker/NewRepo.git'
          }
    }

    stage(Build){
      steps {
        bat 'mvn clean compile'
      }
    }
    
    stage('Test'){
      steps{
        echo 'Running Unit tests..'
        bat 'mvn test'
      }
    }
    
    stage('package'){
      steps {
        bat 'mvn package'
      }
      post {
        success {
          archiveArtifacts artifacts: 'target/*.jar',fingeprint: true
        }
      }
    }
  }
}
